name: Publish packages

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  publish-jvm:
    name: Publish JVM Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to Github Packages
        run: ./gradlew publishJvmPublicationToGitHubPackagesRepository

  publish-js:
    name: Publish JS Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to NPM
        run: |
          ./gradlew assembleJsPackage
          cp "LICENSE" "build/packages/js/LICENSE"
          ./gradlew publishJsPackageToNpmjsRegistry
        env:
          npm_token: ${{ secrets.NPM_TOKEN }}
        
  

